// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmx-B9ma-xh1Dnt70i59bJyFIZw_-4Aog',
    appId: '1:352069183248:web:c69ff59649521a0200a795',
    messagingSenderId: '352069183248',
    projectId: 'read-share-disertatie',
    authDomain: 'read-share-disertatie.firebaseapp.com',
    storageBucket: 'read-share-disertatie.firebasestorage.app',
    measurementId: 'G-JPHC4KGT1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqAd5QdPPfDybGHM0CcwnusbBLZA4PIM',
    appId: '1:352069183248:android:2bee00c4a8e82b1500a795',
    messagingSenderId: '352069183248',
    projectId: 'read-share-disertatie',
    storageBucket: 'read-share-disertatie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPO1ysTZqCr6KdZxzvVnd0A7lFrwAAW0',
    appId: '1:352069183248:ios:89d1e3c1ded77c2500a795',
    messagingSenderId: '352069183248',
    projectId: 'read-share-disertatie',
    storageBucket: 'read-share-disertatie.firebasestorage.app',
    iosBundleId: 'com.example.readShareDisertatieWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPO1ysTZqCr6KdZxzvVnd0A7lFrwAAW0',
    appId: '1:352069183248:ios:89d1e3c1ded77c2500a795',
    messagingSenderId: '352069183248',
    projectId: 'read-share-disertatie',
    storageBucket: 'read-share-disertatie.firebasestorage.app',
    iosBundleId: 'com.example.readShareDisertatieWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmx-B9ma-xh1Dnt70i59bJyFIZw_-4Aog',
    appId: '1:352069183248:web:22aefa1d53991da900a795',
    messagingSenderId: '352069183248',
    projectId: 'read-share-disertatie',
    authDomain: 'read-share-disertatie.firebaseapp.com',
    storageBucket: 'read-share-disertatie.firebasestorage.app',
    measurementId: 'G-TR0K1Q2MK5',
  );
}
